//! AUTO-GENERATED by `lithe-gpui/tools/generate-idea-icons.mjs` —— **不要手改本文件**。
//!
//! 再生成：`node lithe-gpui/tools/generate-idea-icons.mjs`（校验：加 `--check`，退出码 0 表示产物与
//! 文件系统一致）。常量名沿用旧前端那份 Vite 清单（`idea-assets.generated.ts`，**已删除**，
//! 内容见 git 历史 `d13b254a`）的历史命名，但名字与别名由生成器按文件名推导；值是
//! [`AssetSource`] 的**资源路径**而不是打包器 URL。gpui 侧的等价物就是本文件。
//!
//! 常量的 `light` / `dark` 是**给 `gpui::svg().path(..)` 用的路径字符串**（AssetSource 键），
//! 不是文件系统路径。渲染入口与主题选择见 `lithe-gpui-app` 的 `assets` 模块：
//! `lithe_gpui_shared::icons::idea_icon(icon, is_dark)`。
//!
//! 共 79 个图标（其中 78 个有真实的 `_dark.svg` 变体，其余 `dark` 回落 light，
//! 由 [`IdeaIcon::has_dark`] 区分）。路径全部以 `ui-icons/idea/` 为前缀，避免与 gpui-kit
//! `AllAssets` 的 `icons/…`（Lucide 字形）在同一 `AssetSource` 里撞名。
//!
//! **与旧前端命名的对应关系**：旧前端那份 Vite 清单（`idea-assets.generated.ts`，**已删除**）
//! 有 95 个显示名，但只对应 79 张 SVG —— 一张 SVG 常被多个显示名共用（如
//! `CaretDownIcon` 与 `ChevronDownIcon` 都指 `chevronDown.svg`）。本模块为每张 SVG 出一个规范
//! 常量，其余显示名全部保留在 [`ALIASES`]，所以那 95 个显示名一个都没丢。

/// 一个 IntelliJ `expui` 图标在浅色 / 深色主题下的两个资源路径。
///
/// 两个字段都是 `AssetSource` 的键（相对 `lithe-gpui/assets/`），可直接传给
/// `gpui::svg().path(..)`；`gpui-kit` 的 `IconName`（Lucide）走另一条路径 `icons/…`。
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct IdeaIcon {
    /// 浅色主题使用的 SVG 资源路径。
    pub light: &'static str,
    /// 深色主题使用的 SVG 资源路径；没有真实 dark 变体时等于 `light`。
    pub dark: &'static str,
    /// `dark` 是否是磁盘上真实存在的 `_dark.svg`（`false` 表示 `dark` 是 `light` 的回落值）。
    pub has_dark: bool,
}

impl IdeaIcon {
    /// 按当前主题明暗挑路径。`dark` 为 `true` 时取深色变体，否则取浅色。
    pub const fn path(&self, dark: bool) -> &'static str {
        if dark {
            self.dark
        } else {
            self.light
        }
    }
}

/// 全部图标，顺序与常量声明一致（按常量名字典序）。
pub const ALL: [IdeaIcon; 79] = [
    ARCHIVE_ICON,
    ARROW_CLOCKWISE_ICON,
    ARROW_COUNTER_CLOCKWISE_ICON,
    ARROW_DOWN_ICON,
    ARROW_LEFT_ICON,
    ARROW_RIGHT_ICON,
    ARROW_SQUARE_OUT_ICON,
    ARROW_UP_ICON,
    BELL_ICON,
    BOOK_OPEN_ICON,
    BOOKMARK_ICON,
    BUG_ICON,
    CARET_DOWN_ICON,
    CARET_LEFT_ICON,
    CARET_RIGHT_ICON,
    CARET_UP_ICON,
    CHAT_CIRCLE_TEXT_ICON,
    CHECK_ICON,
    CHECK_CIRCLE_ICON,
    CLOCK_COUNTER_CLOCKWISE_ICON,
    COLUMNS_ICON,
    COPY_ICON,
    DATABASE_ICON,
    DOTS_THREE_ICON,
    DOWNLOAD_ICON,
    EYE_ICON,
    EYE_SLASH_ICON,
    FILE_ICON,
    FILE_PLUS_ICON,
    FILES_ICON,
    FLOPPY_DISK_ICON,
    FOLDER_ICON,
    FOLDER_PLUS_ICON,
    FUNCTION_ICON,
    FUNNEL_ICON,
    GEAR_ICON,
    GIT_BRANCH_ICON,
    GIT_COMMIT_ICON,
    GIT_DIFF_ICON,
    GIT_MERGE_ICON,
    GLOBE_HEMISPHERE_WEST_ICON,
    HASH_ICON,
    HOUSE_ICON,
    IMAGE_ICON,
    INFO_ICON,
    KEYBOARD_ICON,
    LIGHTBULB_ICON,
    LIGHTNING_ICON,
    LOCK_ICON,
    LOCK_OPEN_ICON,
    MAGNIFYING_GLASS_ICON,
    MAGNIFYING_GLASS_MINUS_ICON,
    MAGNIFYING_GLASS_PLUS_ICON,
    MINUS_ICON,
    MONITOR_ICON,
    PALETTE_ICON,
    PAUSE_ICON,
    PEN_ICON,
    PLAY_ICON,
    PLUS_ICON,
    PUSH_PIN_ICON,
    QUESTION_ICON,
    REFRESH_ICON,
    ROWS_ICON,
    SCISSORS_ICON,
    SIDEBAR_SIMPLE_ICON,
    SIGN_OUT_ICON,
    STOP_ICON,
    TABLE_ICON,
    TRANSLATE_ICON,
    TRASH_ICON,
    TREE_STRUCTURE_ICON,
    UPLOAD_ICON,
    USER_ICON,
    USERS_THREE_ICON,
    WARNING_CIRCLE_ICON,
    WRENCH_ICON,
    X_ICON,
    XCIRCLE_ICON,
];

/// `ui-icons/idea/expui/fileTypes/archive.svg` / `ui-icons/idea/expui/fileTypes/archive_dark.svg`
pub const ARCHIVE_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/fileTypes/archive.svg",
    dark: "ui-icons/idea/expui/fileTypes/archive_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/redo.svg` / `ui-icons/idea/expui/general/redo_dark.svg`
pub const ARROW_CLOCKWISE_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/redo.svg",
    dark: "ui-icons/idea/expui/general/redo_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/undo.svg` / `ui-icons/idea/expui/general/undo_dark.svg`
pub const ARROW_COUNTER_CLOCKWISE_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/undo.svg",
    dark: "ui-icons/idea/expui/general/undo_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/down.svg` / `ui-icons/idea/expui/general/down_dark.svg`
pub const ARROW_DOWN_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/down.svg",
    dark: "ui-icons/idea/expui/general/down_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/left.svg` / `ui-icons/idea/expui/general/left_dark.svg`
pub const ARROW_LEFT_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/left.svg",
    dark: "ui-icons/idea/expui/general/left_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/right.svg` / `ui-icons/idea/expui/general/right_dark.svg`
pub const ARROW_RIGHT_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/right.svg",
    dark: "ui-icons/idea/expui/general/right_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/ide/externalLink.svg` / `ui-icons/idea/expui/ide/externalLink_dark.svg`
pub const ARROW_SQUARE_OUT_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/ide/externalLink.svg",
    dark: "ui-icons/idea/expui/ide/externalLink_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/up.svg` / `ui-icons/idea/expui/general/up_dark.svg`
pub const ARROW_UP_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/up.svg",
    dark: "ui-icons/idea/expui/general/up_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/toolwindows/notifications.svg` / `ui-icons/idea/expui/toolwindows/notifications_dark.svg`
pub const BELL_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/toolwindows/notifications.svg",
    dark: "ui-icons/idea/expui/toolwindows/notifications_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/toolwindows/documentation.svg` / `ui-icons/idea/expui/toolwindows/documentation_dark.svg`
pub const BOOK_OPEN_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/toolwindows/documentation.svg",
    dark: "ui-icons/idea/expui/toolwindows/documentation_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/bookmarks/bookmark.svg` / `ui-icons/idea/expui/bookmarks/bookmark_dark.svg`
pub const BOOKMARK_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/bookmarks/bookmark.svg",
    dark: "ui-icons/idea/expui/bookmarks/bookmark_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/run/debug.svg` / `ui-icons/idea/expui/run/debug_dark.svg`
pub const BUG_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/run/debug.svg",
    dark: "ui-icons/idea/expui/run/debug_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/chevronDown.svg` / `ui-icons/idea/expui/general/chevronDown_dark.svg`
pub const CARET_DOWN_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/chevronDown.svg",
    dark: "ui-icons/idea/expui/general/chevronDown_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/chevronLeft.svg` / `ui-icons/idea/expui/general/chevronLeft_dark.svg`
pub const CARET_LEFT_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/chevronLeft.svg",
    dark: "ui-icons/idea/expui/general/chevronLeft_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/chevronRight.svg` / `ui-icons/idea/expui/general/chevronRight_dark.svg`
pub const CARET_RIGHT_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/chevronRight.svg",
    dark: "ui-icons/idea/expui/general/chevronRight_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/chevronUp.svg` / `ui-icons/idea/expui/general/chevronUp_dark.svg`
pub const CARET_UP_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/chevronUp.svg",
    dark: "ui-icons/idea/expui/general/chevronUp_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/toolwindows/messages.svg` / `ui-icons/idea/expui/toolwindows/messages_dark.svg`
pub const CHAT_CIRCLE_TEXT_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/toolwindows/messages.svg",
    dark: "ui-icons/idea/expui/toolwindows/messages_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/greenCheckmark.svg` / `ui-icons/idea/expui/general/greenCheckmark_dark.svg`
pub const CHECK_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/greenCheckmark.svg",
    dark: "ui-icons/idea/expui/general/greenCheckmark_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/successDialog.svg` / `ui-icons/idea/expui/general/successDialog_dark.svg`
pub const CHECK_CIRCLE_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/successDialog.svg",
    dark: "ui-icons/idea/expui/general/successDialog_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/history.svg` / `ui-icons/idea/expui/general/history_dark.svg`
pub const CLOCK_COUNTER_CLOCKWISE_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/history.svg",
    dark: "ui-icons/idea/expui/general/history_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/splitVertically.svg` / `ui-icons/idea/expui/general/splitVertically_dark.svg`
pub const COLUMNS_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/splitVertically.svg",
    dark: "ui-icons/idea/expui/general/splitVertically_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/copy.svg` / `ui-icons/idea/expui/general/copy_dark.svg`
pub const COPY_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/copy.svg",
    dark: "ui-icons/idea/expui/general/copy_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/toolwindows/toolWindowDataView.svg` / `ui-icons/idea/expui/toolwindows/toolWindowDataView_dark.svg`
pub const DATABASE_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/toolwindows/toolWindowDataView.svg",
    dark: "ui-icons/idea/expui/toolwindows/toolWindowDataView_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/moreHorizontal.svg` / `ui-icons/idea/expui/general/moreHorizontal_dark.svg`
pub const DOTS_THREE_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/moreHorizontal.svg",
    dark: "ui-icons/idea/expui/general/moreHorizontal_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/download.svg` / `ui-icons/idea/expui/general/download_dark.svg`
pub const DOWNLOAD_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/download.svg",
    dark: "ui-icons/idea/expui/general/download_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/show.svg` / `ui-icons/idea/expui/general/show_dark.svg`
pub const EYE_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/show.svg",
    dark: "ui-icons/idea/expui/general/show_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/hide.svg` / `ui-icons/idea/expui/general/hide_dark.svg`
pub const EYE_SLASH_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/hide.svg",
    dark: "ui-icons/idea/expui/general/hide_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/fileTypes/text.svg`（无 dark 变体）
pub const FILE_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/fileTypes/text.svg",
    dark: "ui-icons/idea/fileTypes/text.svg",
    has_dark: false,
};
/// `ui-icons/idea/expui/actions/addFile.svg` / `ui-icons/idea/expui/actions/addFile_dark.svg`
pub const FILE_PLUS_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/actions/addFile.svg",
    dark: "ui-icons/idea/expui/actions/addFile_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/listFiles.svg` / `ui-icons/idea/expui/general/listFiles_dark.svg`
pub const FILES_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/listFiles.svg",
    dark: "ui-icons/idea/expui/general/listFiles_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/save.svg` / `ui-icons/idea/expui/general/save_dark.svg`
pub const FLOPPY_DISK_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/save.svg",
    dark: "ui-icons/idea/expui/general/save_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/nodes/folder.svg` / `ui-icons/idea/expui/nodes/folder_dark.svg`
pub const FOLDER_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/nodes/folder.svg",
    dark: "ui-icons/idea/expui/nodes/folder_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/actions/newFolder.svg` / `ui-icons/idea/expui/actions/newFolder_dark.svg`
pub const FOLDER_PLUS_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/actions/newFolder.svg",
    dark: "ui-icons/idea/expui/actions/newFolder_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/nodes/function.svg` / `ui-icons/idea/expui/nodes/function_dark.svg`
pub const FUNCTION_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/nodes/function.svg",
    dark: "ui-icons/idea/expui/nodes/function_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/filter.svg` / `ui-icons/idea/expui/general/filter_dark.svg`
pub const FUNNEL_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/filter.svg",
    dark: "ui-icons/idea/expui/general/filter_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/settings.svg` / `ui-icons/idea/expui/general/settings_dark.svg`
pub const GEAR_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/settings.svg",
    dark: "ui-icons/idea/expui/general/settings_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/vcs/branch.svg` / `ui-icons/idea/vcs/branch_dark.svg`
pub const GIT_BRANCH_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/vcs/branch.svg",
    dark: "ui-icons/idea/vcs/branch_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/vcs/commit.svg` / `ui-icons/idea/expui/vcs/commit_dark.svg`
pub const GIT_COMMIT_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/vcs/commit.svg",
    dark: "ui-icons/idea/expui/vcs/commit_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/vcs/diff.svg` / `ui-icons/idea/expui/vcs/diff_dark.svg`
pub const GIT_DIFF_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/vcs/diff.svg",
    dark: "ui-icons/idea/expui/vcs/diff_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/vcs/merge.svg` / `ui-icons/idea/expui/vcs/merge_dark.svg`
pub const GIT_MERGE_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/vcs/merge.svg",
    dark: "ui-icons/idea/expui/vcs/merge_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/toolwindows/web.svg` / `ui-icons/idea/expui/toolwindows/web_dark.svg`
pub const GLOBE_HEMISPHERE_WEST_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/toolwindows/web.svg",
    dark: "ui-icons/idea/expui/toolwindows/web_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/hashtag.svg` / `ui-icons/idea/expui/general/hashtag_dark.svg`
pub const HASH_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/hashtag.svg",
    dark: "ui-icons/idea/expui/general/hashtag_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/javaee/home.svg` / `ui-icons/idea/expui/javaee/home_dark.svg`
pub const HOUSE_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/javaee/home.svg",
    dark: "ui-icons/idea/expui/javaee/home_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/fileTypes/image.svg` / `ui-icons/idea/expui/fileTypes/image_dark.svg`
pub const IMAGE_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/fileTypes/image.svg",
    dark: "ui-icons/idea/expui/fileTypes/image_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/informationDialog.svg` / `ui-icons/idea/expui/general/informationDialog_dark.svg`
pub const INFO_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/informationDialog.svg",
    dark: "ui-icons/idea/expui/general/informationDialog_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/keyboard.svg` / `ui-icons/idea/expui/general/keyboard_dark.svg`
pub const KEYBOARD_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/keyboard.svg",
    dark: "ui-icons/idea/expui/general/keyboard_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/actions/realIntentionBulb.svg` / `ui-icons/idea/expui/actions/realIntentionBulb_dark.svg`
pub const LIGHTBULB_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/actions/realIntentionBulb.svg",
    dark: "ui-icons/idea/expui/actions/realIntentionBulb_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/actions/lightning.svg` / `ui-icons/idea/expui/actions/lightning_dark.svg`
pub const LIGHTNING_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/actions/lightning.svg",
    dark: "ui-icons/idea/expui/actions/lightning_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/locked.svg` / `ui-icons/idea/expui/general/locked_dark.svg`
pub const LOCK_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/locked.svg",
    dark: "ui-icons/idea/expui/general/locked_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/unlocked.svg` / `ui-icons/idea/expui/general/unlocked_dark.svg`
pub const LOCK_OPEN_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/unlocked.svg",
    dark: "ui-icons/idea/expui/general/unlocked_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/search.svg` / `ui-icons/idea/expui/general/search_dark.svg`
pub const MAGNIFYING_GLASS_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/search.svg",
    dark: "ui-icons/idea/expui/general/search_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/image/zoomOut.svg` / `ui-icons/idea/expui/image/zoomOut_dark.svg`
pub const MAGNIFYING_GLASS_MINUS_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/image/zoomOut.svg",
    dark: "ui-icons/idea/expui/image/zoomOut_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/image/zoomIn.svg` / `ui-icons/idea/expui/image/zoomIn_dark.svg`
pub const MAGNIFYING_GLASS_PLUS_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/image/zoomIn.svg",
    dark: "ui-icons/idea/expui/image/zoomIn_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/remove.svg` / `ui-icons/idea/expui/general/remove_dark.svg`
pub const MINUS_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/remove.svg",
    dark: "ui-icons/idea/expui/general/remove_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/nodes/desktop.svg` / `ui-icons/idea/expui/nodes/desktop_dark.svg`
pub const MONITOR_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/nodes/desktop.svg",
    dark: "ui-icons/idea/expui/nodes/desktop_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/toolwindows/palette.svg` / `ui-icons/idea/expui/toolwindows/palette_dark.svg`
pub const PALETTE_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/toolwindows/palette.svg",
    dark: "ui-icons/idea/expui/toolwindows/palette_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/run/pause.svg` / `ui-icons/idea/expui/run/pause_dark.svg`
pub const PAUSE_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/run/pause.svg",
    dark: "ui-icons/idea/expui/run/pause_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/edit.svg` / `ui-icons/idea/expui/general/edit_dark.svg`
pub const PEN_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/edit.svg",
    dark: "ui-icons/idea/expui/general/edit_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/run/run.svg` / `ui-icons/idea/expui/run/run_dark.svg`
pub const PLAY_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/run/run.svg",
    dark: "ui-icons/idea/expui/run/run_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/add.svg` / `ui-icons/idea/expui/general/add_dark.svg`
pub const PLUS_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/add.svg",
    dark: "ui-icons/idea/expui/general/add_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/pin.svg` / `ui-icons/idea/expui/general/pin_dark.svg`
pub const PUSH_PIN_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/pin.svg",
    dark: "ui-icons/idea/expui/general/pin_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/questionDialog.svg` / `ui-icons/idea/expui/general/questionDialog_dark.svg`
pub const QUESTION_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/questionDialog.svg",
    dark: "ui-icons/idea/expui/general/questionDialog_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/refresh.svg` / `ui-icons/idea/expui/general/refresh_dark.svg`
pub const REFRESH_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/refresh.svg",
    dark: "ui-icons/idea/expui/general/refresh_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/splitHorizontally.svg` / `ui-icons/idea/expui/general/splitHorizontally_dark.svg`
pub const ROWS_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/splitHorizontally.svg",
    dark: "ui-icons/idea/expui/general/splitHorizontally_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/cut.svg` / `ui-icons/idea/expui/general/cut_dark.svg`
pub const SCISSORS_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/cut.svg",
    dark: "ui-icons/idea/expui/general/cut_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/layout.svg` / `ui-icons/idea/expui/general/layout_dark.svg`
pub const SIDEBAR_SIMPLE_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/layout.svg",
    dark: "ui-icons/idea/expui/general/layout_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/exit.svg` / `ui-icons/idea/expui/general/exit_dark.svg`
pub const SIGN_OUT_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/exit.svg",
    dark: "ui-icons/idea/expui/general/exit_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/run/stop.svg` / `ui-icons/idea/expui/run/stop_dark.svg`
pub const STOP_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/run/stop.svg",
    dark: "ui-icons/idea/expui/run/stop_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/nodes/dataTables.svg` / `ui-icons/idea/expui/nodes/dataTables_dark.svg`
pub const TABLE_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/nodes/dataTables.svg",
    dark: "ui-icons/idea/expui/nodes/dataTables_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/language.svg` / `ui-icons/idea/expui/general/language_dark.svg`
pub const TRANSLATE_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/language.svg",
    dark: "ui-icons/idea/expui/general/language_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/delete.svg` / `ui-icons/idea/expui/general/delete_dark.svg`
pub const TRASH_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/delete.svg",
    dark: "ui-icons/idea/expui/general/delete_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/tree.svg` / `ui-icons/idea/expui/general/tree_dark.svg`
pub const TREE_STRUCTURE_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/tree.svg",
    dark: "ui-icons/idea/expui/general/tree_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/upload.svg` / `ui-icons/idea/expui/general/upload_dark.svg`
pub const UPLOAD_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/upload.svg",
    dark: "ui-icons/idea/expui/general/upload_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/user.svg` / `ui-icons/idea/expui/general/user_dark.svg`
pub const USER_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/user.svg",
    dark: "ui-icons/idea/expui/general/user_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/groups.svg` / `ui-icons/idea/expui/general/groups_dark.svg`
pub const USERS_THREE_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/groups.svg",
    dark: "ui-icons/idea/expui/general/groups_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/warningDialog.svg` / `ui-icons/idea/expui/general/warningDialog_dark.svg`
pub const WARNING_CIRCLE_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/warningDialog.svg",
    dark: "ui-icons/idea/expui/general/warningDialog_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/externalTools.svg` / `ui-icons/idea/expui/general/externalTools_dark.svg`
pub const WRENCH_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/externalTools.svg",
    dark: "ui-icons/idea/expui/general/externalTools_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/close.svg` / `ui-icons/idea/expui/general/close_dark.svg`
pub const X_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/close.svg",
    dark: "ui-icons/idea/expui/general/close_dark.svg",
    has_dark: true,
};
/// `ui-icons/idea/expui/general/errorDialog.svg` / `ui-icons/idea/expui/general/errorDialog_dark.svg`
pub const XCIRCLE_ICON: IdeaIcon = IdeaIcon {
    light: "ui-icons/idea/expui/general/errorDialog.svg",
    dark: "ui-icons/idea/expui/general/errorDialog_dark.svg",
    has_dark: true,
};

/// 旧前端那份 Vite 清单（`idea-assets.generated.ts`，**已删除**）里那些**别名**显示名 → 规范常量。
///
/// 键就是那份清单的 `ideaIconAssets` 键（`"ChevronDownIcon"` 这种**原样**未截断的显示名）；
/// 别名由生成器按 `lithe-gpui/tools/idea-icon-mappings.json` 推导，不再读那份 TS。
/// 只为迁移期与文档对照保留；新代码应该直接用规范常量（[`ALL`] 里的那些）。
pub const ALIASES: [(&str, IdeaIcon); 16] = [
    ("ChevronDownIcon", CARET_DOWN_ICON),
    ("ChevronLeftIcon", CARET_LEFT_ICON),
    ("ChevronRightIcon", CARET_RIGHT_ICON),
    ("ChevronUpIcon", CARET_UP_ICON),
    ("CopySimpleIcon", COPY_ICON),
    ("DownloadSimpleIcon", DOWNLOAD_ICON),
    ("FileTextIcon", FILE_ICON),
    ("GearSixIcon", GEAR_ICON),
    ("GlobeIcon", GLOBE_HEMISPHERE_WEST_ICON),
    ("OpenExternalIcon", ARROW_SQUARE_OUT_ICON),
    ("PencilIcon", PEN_ICON),
    ("PencilLineIcon", PEN_ICON),
    ("PencilSimpleIcon", PEN_ICON),
    ("PencilSimpleLineIcon", PEN_ICON),
    ("UploadSimpleIcon", UPLOAD_ICON),
    ("WarningIcon", WARNING_CIRCLE_ICON),
];
