[package]
name = "lithe-gpui-workbench"
version = "0.0.1"
edition = "2024"
publish = false

[dependencies]
gpui-kit = "0.6"
lithe-gpui-editor = { path = "../editor" }
lithe-gpui-explorer = { path = "../explorer" }
lithe-gpui-git = { path = "../git" }
lithe-gpui-shared = { path = "../shared" }
lithe-gpui-terminal = { path = "../terminal" }
